export const sampleOpportunities = [
  {
    title: 'Commercial Farming Project in the West Region',
    description: 'This initiative is part of the National Youth Employment Agency\'s flagship program to modernize Cameroon\'s agricultural sector. Located in the fertile highlands of the West Region, the Commercial Farming Project focuses on sustainable large-scale production of high-value crops including pineapples, coffee, and local tubers for both domestic markets and international export.\n\nSelected participants will be integrated into a high-tech ecosystem featuring automated irrigation systems, modern processing facilities, and a robust cold-chain logistics network. This project aims to empower 500 young professionals through direct employment and specialized training in agribusiness management.',
    category: 'Agriculture',
    location: 'Bafoussam, West',
    region: 'West',
    salary_min: 250000,
    salary_max: 450000,
    salary_currency: 'CFA',
    duration: '12 Months',
    capacity: 50,
    available_spots: 15,
    required_skills: ['Agribusiness Strategy & Planning', 'Supply Chain & Logistics Management', 'Sustainable Agricultural Practices', 'Project Coordination'],
    image_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=500&h=300&fit=crop',
    employer_name: 'Ministry of Agriculture & Rural Development',
    status: 'active',
  },
  {
    title: 'Sustainable Farm Manager',
    description: 'Leading agricultural hub in the North-West region looking for a youth supervisor to manage sustainable farming operations. This is a great opportunity to develop your agribusiness skills and leadership abilities while contributing to food security in Cameroon.',
    category: 'Agriculture',
    location: 'Bamenda, North-West',
    region: 'North-West',
    salary_min: 300000,
    salary_max: 500000,
    salary_currency: 'CFA',
    duration: 'Full-time',
    capacity: 30,
    available_spots: 8,
    required_skills: ['Farm Management', 'Leadership', 'Sustainability Practices', 'Data Analysis'],
    image_url: 'https://images.unsplash.com/photo-1500382017468-f049863256f0?w=500&h=300&fit=crop',
    employer_name: 'Sustainable Farms Ltd',
    status: 'active',
  },
  {
    title: 'Junior Frontend Developer',
    description: 'Join the National Digital Initiative to build citizen-facing portals. We\'re seeking talented React developers to work on high-impact government digital transformation projects. You\'ll work with modern tech stacks and contribute to Cameroon\'s digital future.',
    category: 'Tech',
    location: 'Yaoundé, Centre',
    region: 'Centre',
    salary_min: 400000,
    salary_max: 650000,
    salary_currency: 'CFA',
    duration: 'Hybrid',
    capacity: 20,
    available_spots: 5,
    required_skills: ['React', 'JavaScript', 'CSS', 'Web Development', 'UI/UX'],
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    employer_name: 'National Digital Initiative',
    status: 'active',
  },
  {
    title: 'Software Engineering Technician',
    description: 'Tech startup focused on software solutions for the Silicon Mountain ecosystem. We\'re building innovative products and need passionate developers to join our team in Buea.',
    category: 'Tech',
    location: 'Buea, South-West',
    region: 'South-West',
    salary_min: 350000,
    salary_max: 600000,
    salary_currency: 'CFA',
    duration: 'Full-time',
    capacity: 15,
    available_spots: 3,
    required_skills: ['Python', 'JavaScript', 'Database Design', 'Problem Solving'],
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    employer_name: 'Tech Innovations Hub',
    status: 'active',
  },
  {
    title: 'Certified Welding & Metal Works Training',
    description: 'Ministry-approved vocational program designed to equip youth with professional welding skills. This comprehensive 3-month course covers industrial welding, safety protocols, and job placement assistance upon completion.',
    category: 'Training',
    location: 'Douala, Littoral',
    region: 'Littoral',
    salary_min: 0,
    salary_max: 0,
    salary_currency: 'CFA',
    duration: 'Part-time',
    capacity: 100,
    available_spots: 45,
    required_skills: ['Technical Aptitude', 'Attention to Detail', 'Physical Fitness', 'Safety Awareness'],
    image_url: 'https://images.unsplash.com/photo-1487528278519-e21cc028cb29?w=500&h=300&fit=crop',
    employer_name: 'Ministry of Employment',
    status: 'active',
  },
  {
    title: 'Retail Manager - Express Store',
    description: 'Looking for an energetic retail manager to oversee daily operations at our express store in downtown Yaoundé. You\'ll manage staff, inventory, and customer satisfaction while driving sales growth.',
    category: 'Local Jobs',
    location: 'Yaoundé, Centre',
    region: 'Centre',
    salary_min: 200000,
    salary_max: 350000,
    salary_currency: 'CFA',
    duration: 'Full-time',
    capacity: 10,
    available_spots: 2,
    required_skills: ['Retail Management', 'Customer Service', 'Inventory Control', 'Team Leadership'],
    image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    employer_name: 'Express Retail Group',
    status: 'active',
  },
  {
    title: 'Construction Site Manager - Infrastructure Project',
    description: 'Major infrastructure project in Douala seeking experienced site managers. Oversee construction teams, ensure project timelines, and maintain safety standards on a large-scale development project.',
    category: 'Construction',
    location: 'Douala, Littoral',
    region: 'Littoral',
    salary_min: 450000,
    salary_max: 750000,
    salary_currency: 'CFA',
    duration: 'Full-time',
    capacity: 25,
    available_spots: 6,
    required_skills: ['Project Management', 'Civil Engineering', 'Team Leadership', 'Safety Management', 'Budget Control'],
    image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=500&h=300&fit=crop',
    employer_name: 'BuildCam Infrastructure',
    status: 'active',
  },
  {
    title: 'Healthcare Worker - Community Health Centre',
    description: 'Community health center in Yaoundé is recruiting healthcare workers to provide basic medical services, health education, and patient care in underserved communities. Great opportunity to make a social impact.',
    category: 'Healthcare',
    location: 'Yaoundé, Centre',
    region: 'Centre',
    salary_min: 180000,
    salary_max: 320000,
    salary_currency: 'CFA',
    duration: 'Full-time',
    capacity: 20,
    available_spots: 7,
    required_skills: ['Patient Care', 'Health Education', 'First Aid', 'Communication', 'Basic Medical Knowledge'],
    image_url: 'https://images.unsplash.com/photo-1631217b9b90-afa2e2acb200?w=500&h=300&fit=crop',
    employer_name: 'Community Health Services',
    status: 'active',
  },
];
